Issue 1 see breed list
katiefugate/ajax-project pull request #6
Opened 2021-04-13 22:59 UTC by katiefugate

<img width="1186" alt="Screen Shot 2021-04-13 at 3 48 21 PM" src="https://user-images.githubusercontent.com/78885956/114631343-3dfa8d80-9c71-11eb-8072-c488f5fa9630.png">
![Screen Shot 2021-04-13 at 3 54 46 PM](https://user-images.githubusercontent.com/78885956/114631355-43f06e80-9c71-11eb-8c65-6290657d27aa.png)

2021-04-13 23:36 UTC, katiefugate commented
<img width="1261" alt="Screen Shot 2021-04-13 at 4 33 12 PM" src="https://user-images.githubusercontent.com/78885956/114633890-42757500-9c76-11eb-911c-ccf4c1f1ea9c.png">
<img width="487" alt="Screen Shot 2021-04-13 at 4 33 28 PM" src="https://user-images.githubusercontent.com/78885956/114633909-499c8300-9c76-11eb-9663-10b6a539a8cc.png">

2021-04-13 23:38 UTC, codingcodymiller requested changes

2021-04-13 23:38 UTC, codingcodymiller commented on css/layout.css
> +}
Why the absolute positioning here? What is this for?

2021-04-13 23:38 UTC, codingcodymiller commented on css/layout.css
> +  }
😱 😱 😱 😱

2021-04-14 00:12 UTC, katiefugate commented
<img width="1180" alt="Screen Shot 2021-04-13 at 5 08 49 PM" src="https://user-images.githubusercontent.com/78885956/114636226-5c658680-9c7b-11eb-94fd-22a7c4df8078.png">
<img width="485" alt="Screen Shot 2021-04-13 at 5 10 19 PM" src="https://user-images.githubusercontent.com/78885956/114636235-61c2d100-9c7b-11eb-8ddd-da15c7d639a0.png">

2021-04-14 00:13 UTC, codingcodymiller approved these changes

2021-04-14 00:13 UTC, merged